apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: postgres
    release: {{ .Release.Name }}
type: Opaque
data:
  password: {{ .Values.postgres.password | b64enc }}
