apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-worker
  namespace: {{ .Values.namespace }}
  labels:
    app: worker
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.worker.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: worker
    release: {{ .Release.Name }}
