apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  namespace: blog
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: blog-https-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - 5xx.engineer
    secretName: blog-prod-tls
  - hosts:
    - blog.5xx.engineer
    secretName: blog-tls
  rules:
  - host: 5xx.engineer
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog
            port:
              number: 80
  - host: blog.5xx.engineer
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-www-redirect
  namespace: blog
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: blog-https-redirect@kubernetescrd,blog-redirect-www@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - www.5xx.engineer
    secretName: blog-www-tls
  rules:
  - host: www.5xx.engineer
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blog
            port:
              number: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: blog
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-www
  namespace: blog
spec:
  redirectRegex:
    regex: "^https://www\\.5xx\\.engineer/(.*)"
    replacement: "https://5xx.engineer/${1}"
    permanent: true
