apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atuin
  namespace: atuin
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: atuin-https-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - atuin.5xx.engineer
    secretName: atuin-prod-tls
  rules:
  - host: atuin.5xx.engineer
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: atuin-server
            port:
              number: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: atuin
spec:
  redirectScheme:
    scheme: https
    permanent: true
